### ISSUE TITLE
Prefabs not spawned in packaged game

### ISSUE THREAD

**Issue by michaelWuensch** [coderespawn/prefabricator-ue4#19]
Hi there,

we developed something in the editor using the plugin and it worked fine. The prefabs are spawned at runtime. Unfortunatelly they are not spawned (or are not visible) when packaging for windows 64 bit platform.
Do we have to do something or is this a bug?

**Comment by michaelWuensch** [comment]
Hi, I now have further investigated it. Here is what I found out:

- Making a simple Prefab containing one mesh works and is also spawned in a packaged game.
- Making a simple PrefabCollection which contains two simple Prefabs like previously created works and is also spawned in a packaged game.
- Making a Prefab that uses 2 instances of the previously generated PrefabCollection works in the editor, but is not spawned in game on runtime.
BUT it is spawned if you first place this complex prefeb on the map.

Therefore I guess it does not correctly reference the prefabs and does not include the meshes in the packaged build.

**Comment by dyanikoglu** [comment]
@coderespawn still no updates?

**Comment by coderespawn** [comment]
Apologies for the delay in fixing this. This has been fixed in the latest build (1.4.0)

The issue was with child prefab references.  When a nested prefab was created, it was not holding a soft reference to the child prefab assets (only a reference in serialized text from).   This made the engine think that the asset was not used and was not shipping it.    You can now properly see all the child prefab assets in the reference viewer and I've confirmed that it works with large nested prefab
